/**
 * load/api.js — Supabase API load test
 *
 * Simulates concurrent QA sessions hitting the Supabase REST API directly:
 *   - Reading reports and items (like multiple team members loading the tool)
 *   - Writing new items (like multiple testers submitting issues)
 *
 * Run:
 *   k6 run tests/load/api.js \
 *     --env SUPABASE_URL=https://duwnavhedpitpfomijcq.supabase.co \
 *     --env SUPABASE_ANON_KEY=<your-anon-key> \
 *     --env REPORT_ID=<existing-report-id>
 *
 * Stages: ramp to 30 VUs (simulating 30 simultaneous testers), hold, ramp down.
 */

import http   from "k6/http";
import { check, sleep } from "k6";
import { Trend, Rate, Counter } from "k6/metrics";
import { uuidv4 } from "https://jslib.k6.io/k6-utils/1.4.0/index.js";

const readLatency  = new Trend("supabase_read_ms");
const writeLatency = new Trend("supabase_write_ms");
const errorRate    = new Rate("errors");
const writes       = new Counter("items_written");

export const options = {
  stages: [
    { duration: "20s", target: 10  },  // ramp up
    { duration: "1m",  target: 30  },  // hold — 30 concurrent testers
    { duration: "30s", target: 50  },  // spike test
    { duration: "20s", target: 0   },  // ramp down
  ],
  thresholds: {
    supabase_read_ms:  ["p(95)<1000"],  // reads under 1s at p95
    supabase_write_ms: ["p(95)<2000"],  // writes under 2s at p95
    errors:            ["rate<0.05"],   // <5% errors
  },
};

const SUPABASE_URL      = __ENV.SUPABASE_URL      || "https://duwnavhedpitpfomijcq.supabase.co";
const SUPABASE_ANON_KEY = __ENV.SUPABASE_ANON_KEY || "";
const REPORT_ID         = __ENV.REPORT_ID         || "test-load-report";

const HEADERS = {
  "Content-Type":  "application/json",
  "apikey":        SUPABASE_ANON_KEY,
  "Authorization": `Bearer ${SUPABASE_ANON_KEY}`,
  "Prefer":        "return=minimal",
};

const READ_HEADERS = Object.assign({}, HEADERS, { "Prefer": "return=representation" });

const CATEGORIES = ["bug", "feature", "improvement", "question"];
const PRIORITIES = ["critical", "high", "medium", "low"];
const TEAM       = ["Shri", "Roshit", "Jhilik", "Amit", "Ritesh", "Harsha"];
const rand       = (arr) => arr[Math.floor(Math.random() * arr.length)];

export function setup() {
  // Ensure the test report exists
  if (!SUPABASE_ANON_KEY) {
    console.warn("⚠️  SUPABASE_ANON_KEY not set — API tests will fail auth checks");
  }
  const res = http.post(
    `${SUPABASE_URL}/rest/v1/reports`,
    JSON.stringify({ id: REPORT_ID, title: "Load Test Session" }),
    { headers: Object.assign({}, HEADERS, { "Prefer": "resolution=ignore-duplicates" }) }
  );
  console.log(`Setup: ensure report exists → ${res.status}`);
}

export default function () {
  // ── READ: load all items for the report ──
  const readRes = http.get(
    `${SUPABASE_URL}/rest/v1/items?report_id=eq.${REPORT_ID}&order=created_at.asc`,
    { headers: READ_HEADERS }
  );
  readLatency.add(readRes.timings.duration);
  errorRate.add(readRes.status !== 200);
  check(readRes, {
    "items read 200":      (r) => r.status === 200,
    "items read fast":     (r) => r.timings.duration < 1000,
    "response is array":   (r) => { try { return Array.isArray(JSON.parse(r.body)); } catch { return false; } },
  });

  sleep(0.5);

  // ── WRITE: insert a new item (simulating a tester submitting an issue) ──
  const item = {
    id:          `load-${uuidv4()}`,
    report_id:   REPORT_ID,
    title:       `[Load Test] Issue ${Date.now()}`,
    description: "Auto-generated by k6 load test",
    category:    rand(CATEGORIES),
    priority:    rand(PRIORITIES),
    status:      "todo",
    raised_by:   rand(TEAM),
    assignee:    rand(TEAM),
    created_at:  new Date().toISOString(),
  };

  const writeRes = http.post(
    `${SUPABASE_URL}/rest/v1/items`,
    JSON.stringify(item),
    { headers: HEADERS }
  );
  writeLatency.add(writeRes.timings.duration);
  errorRate.add(writeRes.status >= 400);
  writes.add(1);
  check(writeRes, {
    "item write 201": (r) => r.status === 201,
    "item write fast": (r) => r.timings.duration < 2000,
  });

  sleep(1);

  // ── STATUS UPDATE: simulate a dev updating item status ──
  // (only ~30% of the time to match realistic usage)
  if (Math.random() < 0.3) {
    const statusRes = http.patch(
      `${SUPABASE_URL}/rest/v1/items?id=eq.${item.id}`,
      JSON.stringify({ status: "in_progress" }),
      { headers: HEADERS }
    );
    check(statusRes, { "status update ok": (r) => r.status === 204 || r.status === 200 });
  }

  sleep(1);
}

export function teardown() {
  // Clean up load test items
  const res = http.del(
    `${SUPABASE_URL}/rest/v1/items?report_id=eq.${REPORT_ID}&title=like.*Load+Test*`,
    null,
    { headers: HEADERS }
  );
  console.log(`Teardown: cleaned load test items → ${res.status}`);
}
